

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: todo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: majimenezaquino/todo-backend
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: todo-volume
        env:
        - name: MONGO_URL
          value: "mongodb://mongo-service:27017/todo-app"
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000
      volumes:
      - name: todo-volume
        persistentVolumeClaim:
          claimName: todo-database-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db
  labels:
    app: todo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
      - name: todo-db
        image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: todo-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000