apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: todo-fronent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-fronent
  template:
    metadata:
      labels:
        app: todo-fronent
    spec:
      containers:
      - name: todo-fronent
        image: majimenezaquino/todo-fronent
        env:
        - name: BACKENDURL
          value: "http://backeend:3000/api/tasks"
        ports:
        - containerPort: 3000
---
---
apiVersion: v1
kind: Service
metadata:
  name: sevice-frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 3000
  selector:
    app: todo-fronent

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: sevice-frontend
            port:
              number: 8080
  - http:
      paths:
      - path: /backend
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 3000