apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-database
spec:
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /home/docker
    type: Directory 
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-database-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
---